# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Page Text')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksearch.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksearch.Book')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksearch.Section'),
        ),
    ]
